#baseURL: 'http://10.30.132.14:1313/'
baseURL: '/'
languageCode: 'en-us'
title: '57+ Blocks'
#theme: 'PaperMod'
theme: 'spectral'

googleAnalytics: 'G-TQNJED2QWD'

#relativeURLs: true
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  custom_scss: 'scss/styles.scss'

  social:
    # this array format is for the nightfall theme, comment out if not using
    -
      key: 0
      name: 'email'
      url: 'mailto:57blocksphilly@gmail.com'
  menu:
    main:
      -
       url: '/'
       title: '57+ Blocks'
      -
       url: '/who-we-are/'
       title: 'Who We Are'
      -
       url: '/news-and-press/'
       title: 'News & Press'
      -
       url: '/about-the-blocks/'
       title: 'About the Blocks'
      -
       url: '/contact/'
       title: 'Contact Us'

languages:
  en:
    languageName: 'English'
    weight: 1
    menu:
      main:
        -
         url: '/'
         title: 'Home'
         name: 'Home'
        -
         url: '/who-we-are/'
         title: 'Who We Are'
         name: 'Who We Are'
        -
         url: '/news-and-press/'
         title: 'News & Press'
         name: 'News & Press'
        -
         url: '/about-the-blocks/'
         title: 'About the Blocks'
         name: 'About the Blocks'
        -
         url: '/contact/'
         title: 'Contact Us'
         name: 'Contact Us'

